language: node_js
node_js:
  - '10'
install:
  - yarn
script:
  - yarn format:check
  - yarn test
  - yarn build
  - yarn yarn audit
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
