import { AbstractShape } from './shape';
import { Vector } from '../spatial';
import { Direction } from '../spatial/direction';
export declare class Rectangle extends AbstractShape {
    readonly x: number;
    readonly y: number;
    readonly width: number;
    readonly height: number;
    static fromBounds(left: number, right: number, top: number, bottom: number): Rectangle;
    static footprint(position: Vector, direction: Direction, size: Vector): Rectangle;
    static centerAt(x: number, y: number, size: number): Rectangle;
    constructor(x: number, y: number, width: number, height: number);
    get left(): number;
    get right(): number;
    get top(): number;
    get bottom(): number;
    get topLeft(): Vector;
    get topRight(): Vector;
    get bottomRight(): Vector;
    get bottomLeft(): Vector;
    get center(): Vector;
    centerOf(direction: Direction): Vector;
    get centerLeft(): Vector;
    get centerRight(): Vector;
    get centerTop(): Vector;
    get centerBottom(): Vector;
    plus(other: Rectangle): Rectangle;
    intersect(other: Rectangle): Rectangle;
    cover(other: Vector): Rectangle;
    getWall(other: Vector): Direction | undefined;
    bounds(): Rectangle;
    containsVector(p: Vector): boolean;
    translate(t: Vector): Rectangle;
    grow(cells?: number): Rectangle;
    shrink(cells?: number): Rectangle;
    all(f: (position: Vector) => boolean): boolean;
}
